---

#[[#########################################################
# VARIABLES QUE SE APLICAN A TODOS LOS ENTORNOS
#########################################################]]#

smtp_server: smtp.vocento.com
